---
spring:
  main:
    log-startup-info: false
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/filter_data
    username:
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logbook:
  predicate:
    include:
      - path: /api/**

logging:
  level:
    org.zalando.logbook: TRACE

management:
  endpoint:
    health:
      probes:
        enabled: true
